package:
  name: georasters
  version: "0.5.6"

source:
  fn: georasters-0.5.6.tar.gz
  url: https://pypi.python.org/packages/10/11/b7ed774362775d7b20ac019e1695f2a3188040a19a2fb9995dbe2267c677/georasters-0.5.6.tar.gz
  md5: f7aa1abc66628132f709130fd37a1f06
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - georasters = georasters:main
    #
    # Would create an entry point called georasters that calls georasters.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy
    - gdal
    - docopt
    - pandas
    - pyproj
    - scikit-image
    - matplotlib
    - dask
    - libspatialite
    - fiona

  run:
    - python
    - numpy
    - gdal
    - docopt
    - pandas
    - pyproj
    - scikit-image
    - matplotlib
    - dask
    - libspatialite
    - fiona
    - pillow
    - geopandas
    - affine
    - geopy
    - geos
    - proj4
    - pyproj
    - rasterio
    - cartopy
    - click
    - cligj
    - certifi
    - descartes
    - scikit-image
    - shapely
    - rasterstats

test:
  # Python imports
  imports:
    - georasters

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - coverage
    - pyshp >=1.1.4
    - pytest
    - pytest-cov >=2.2.0
    - simplejson
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/ozak/georasters
  license: GNU General Public License v3 or later (GPLv3+)
  summary: 'Tools for working with Geographical Information System Rasters'
  license_family: GPL3

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
