package:
  name: georasters
  version: "0.5.8"

source:
  git_url: https://github.com/ozak/georasters.git
#  fn: georasters-0.5.8.tar.gz
#  url: https://pypi.python.org/packages/fc/c1/8783202a54cd7478d87f784121c726b23a646e1323ef6075d953d529b2c6/georasters-0.5.8.tar.gz
#  md5: f06e84daa0a6f15097772cb88c2b4c71
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch: python
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - georasters = georasters:main
    #
    # Would create an entry point called georasters that calls georasters.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy
    - gdal
    - docopt
    - pandas
    - pyproj
    - scikit-image
    - matplotlib
    - dask
    - libspatialite
    - fiona
    - rasterstats
    - geopandas
    - pysal
    - affine

  run:
    - python
    - numpy
    - gdal
    - pandas
    - docopt
    - gdal
    - pyproj
    - scikit-image
    - matplotlib
    - coverage
    - fiona
    - geopandas
    - pysal
    - affine
    - geopy
    - geos
    - proj4
    - pyproj
    - rasterio
    - cartopy
    - click
    - cligj
    - certifi
    - descartes
    - scikit-image
    - shapely
    - rasterstats

test:
  # Python imports
  imports:
    - georasters

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - coverage
    - pyshp >=1.1.4
    - pytest
    - pytest-cov >=2.2.0
    - simplejson
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/ozak/georasters
  license: GNU General Public License v3 or later (GPLv3+)
  summary: 'Tools for working with Geographical Information System Rasters'
  license_family: GPL3

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
