package:
  name: georasters
  version: "0.5.5"

source:
  fn: georasters-0.5.5.tar.gz
  url: https://pypi.python.org/packages/1c/2d/5c789e1153594e05d14d46c2d8bbf83e105a4017c4e3ca66cc388e991174/georasters-0.5.5.tar.gz
  md5: b9347924ecf2faf3cbf449ce55474d37
#  patches:
   # List any patch files here
   # - fix.patch

build:
  osx_is_app: True
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - georasters = georasters:main
    #
    # Would create an entry point called georasters that calls georasters.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - python.app
    - setuptools
    - numpy
    - gdal
    - docopt
    - pandas
    - pyproj
    - scikit-image
    - matplotlib
    - affine
    - rasterstats
    - pysal
    - geopandas
    - fiona
    - proj4
    - dask
    - pillow
    - libspatialite

  run:
    - python
    - python.app
    - numpy
    - gdal
    - docopt
    - pandas
    - pyproj
    - scikit-image
    - matplotlib
    - affine
    - rasterstats
    - pysal
    - geopandas
    - proj4
    - fiona
    - pillow
    - libspatialite
    - bokeh

test:
  files:
    - test-data.txt
  # Python imports
  #imports:
  #  - georasters

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - coverage
    - pyshp >=1.1.4
    - pytest
    - pytest-cov >=2.2.0
    - simplejson
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/ozak/georasters
  license: GNU General Public License v3 or later (GPLv3+)
  summary: 'Tools for working with Geographical Information System Rasters in Python'
  license_family: GPL3

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
