name: GeoPython37env
channels:
  - conda-forge
  - numba
  - rapidsai
  - mro
  - r
  - defaults
dependencies:
  - python==3.7
  - pip
  - numpy
  - pandas
  - docopt
  - gdal
  - pyproj
  - scikit-image
  - matplotlib-base
  - coverage
  - fiona
  - geopandas
  - pysal
  - affine
  - rasterstats >=0.12
  - pip:
    - googledrivedownloader
