name: GeoPython37env
channels:
  - conda-forge
  - numba
  - rapidsai
  - mro
  - r
  - defaults
dependencies:
  - python==3.7
  - pip
  - python
  - numpy
  - pandas
  - docopt
  - gdal
  - pyproj
  - matplotlib-base
  - coverage
  - fiona
  - geopandas
  - pysal
  - affine
  - rasterstats >=0.12
  - basemap
  - cartopy
  - datashader
  - datashape
  - georasters
  - ipykernel
  - ipyparallel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jupyter
  - jupyterlab
  - numpy
  - openpyxl
  - pandas
  - pandas-datareader
  - pandana
  - pycountry
  - pysal
  - urbanaccess
  - r
  - rstudio
  - r-irkernel
  - statsmodels
  - sympy
  - rpy2
  - rasterio
  - r-tidyr
  - r-tibble
  - r-dplyr
  - rise
  - seaborn
  - scikit-image
  - scikit-learn
  - scipy
  - swifter
  - unidecode
  - urllib3
  - wikipedia
  - xlrd
  - jupyter_contrib_nbextensions
  - pip:
    - linearmodels
    - isounidecode
    - geonamescache
    - geocoder
    - git+https://github.com/jeetsukumaran/DendroPy.git
    - git+https://github.com/dmsul/econtools
    - ecopy
    - geonamescache
    - googledrivedownloader
    - googletrans
    - ipystata
    - isodate
    - isounidecode
    - latexcodec
    - ldpred
    - linearmodels
    - pycountry
    - pylatex
    - pyparsing
    - pyreadstat
    - pytrends
    - stata-kernel
    - tabulate
