package:
  name: descartes
  version: "1.0.2"

source:
  fn: descartes-1.0.2.tar.gz
  url: https://pypi.python.org/packages/52/65/6078084b6b84b8c87730f9ebf825fbcd7f1ba7bf383fbb6f0a8a6d2419af/descartes-1.0.2.tar.gz
  md5: 2af859c63f73ef852c691f46a06e5938
#  patches:
   # List any patch files here
   # - fix.patch

# build:
   noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - descartes = descartes:main
    #
    # Would create an entry point called descartes that calls descartes.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - descartes

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://bitbucket.org/sgillies/descartes/
  license: BSD License
  summary: 'Use geometric objects as matplotlib paths and patches'
  license_family: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
